name: Kapal-Lawd
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1
options:
  bundleIdPrefix: com.Kapal-Lawd
packages:
  SDBeaconScanner:
    url: https://github.com/SagarSDagdu/SDBeaconScanner.git
    from: 0.0.2
targets:
  Kapal-Lawd:
    type: application
    platform: iOS
    info:
        path: Kapal-Lawd/Info.plist
        properties: {}
    sources: [Kapal-Lawd]
    resources: [Resources]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.Kapal-Lawd.Kapal-Lawd
      INFOPLIST_FILE: Kapal-Lawd/Info.plist
      GENERATE_INFOPLIST_FILE: true
    dependencies:
        - package: SDBeaconScanner
  Kapal-LawdTests:
    type: bundle.unit-test
    platform: iOS
    sources: [Kapal-LawdTests]
    dependencies:
      - target: Kapal-Lawd
    settings:
      base:
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Kapal-Lawd.app/Kapal-Lawd"
        BUNDLE_LOADER: "$(TEST_HOST)"
        INFOPLIST_FILE: Kapal-Lawd/Info.plist
        GENERATE_INFOPLIST_FILE: true
schemes:
  Kapal-Lawd:
    build:
      targets:
        Kapal-Lawd: all
        Kapal-LawdTests: all
    test:
      targets:
      - name: Kapal-LawdTests
      gatherCoverageData: true

