name: Kapal-Lawd
settings:
  MARKETING_VERSION: ${MARKETING_VERSION}
  CURRENT_PROJECT_VERSION: ${CURRENT_PROJECT_VERSION}
  DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM_ID}
  SUPABASE_API_KEY: ${SUPABASE_API_KEY}
  SUPABASE_BASE_URL: ${SUPABASE_BASE_URL}
options:
  bundleIdPrefix: com.Kapal-Lawd
  resolvePackagesAutomatically: true
packages:
  SDBeaconScanner:
    url: https://github.com/SagarSDagdu/SDBeaconScanner.git
    from: 0.0.2
  Supabase:
    url: "https://github.com/supabase/supabase-swift.git"
    from: 2.0.0
targets:
  Kapal-Lawd:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    info:
        path: Kapal-Lawd/Info.plist
        properties:
          Privacy - Location Always and When In Use Usage Description: "Your app needs access to your location to provide personalized services even when the app is in the background."
          Privacy - Location When In Use Usage Description: "Your app needs access to your location to provide personalized services when the app is in use."
          NSLocationWhenInUseUsageDescription: "Your app needs access to your location to provide personalized services even when the app is in the background."
          NSLocationAlwaysAndWhenInUseUsageDescription: "Your app needs access to your location to provide personalized services even when the app is in the background."
          NSBluetoothAlwaysUsageDescription: "This app requires continuous access to Bluetooth for background monitoring."
          NSBluetoothPeripheralUsageDescription: "This app requires access to Bluetooth for connecting to peripherals."
          NSAppTransportSecurity:
            NSAllowsArbitraryLoads: true
          UIBackgroundModes:
            - location
            - audio
            - bluetooth-central
            - processing
            - fetch
          BGTaskSchedulerPermittedIdentifiers:
            - "com.Kapal-Lawd.Kapal-Lawd.refresh"
            - "com.Kapal-Lawd.Kapal-Lawd.processing"
          UILaunchScreen:
            UIImageName: ""
          UISupportedInterfaceOrientations:
            - UIInterfaceOrientationPortrait
            - UIInterfaceOrientationPortraitUpsideDown
            - UIInterfaceOrientationLandscapeLeft
            - UIInterfaceOrientationLandscapeRight
          CFBundleIconName: "AppIcon"
          CFBundleDisplayName: "Audium"
          SUPABASE_API_KEY: ${SUPABASE_API_KEY}
          SUPABASE_BASE_URL: ${SUPABASE_BASE_URL}
    sources: [Kapal-Lawd]
    resources: [Resources]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.Kapal-Lawd.Kapal-Lawd
      INFOPLIST_FILE: Kapal-Lawd/Info.plist
      GENERATE_INFOPLIST_FILE: true
      DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM_ID}
    dependencies:
        - package: SDBeaconScanner
        - package: Supabase
  Kapal-LawdTests:
    type: bundle.unit-test
    platform: iOS
    sources: [Kapal-LawdTests]
    dependencies:
      - target: Kapal-Lawd
    settings:
      base:
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Kapal-Lawd.app/Kapal-Lawd"
        BUNDLE_LOADER: "$(TEST_HOST)"
        INFOPLIST_FILE: Kapal-Lawd/Info.plist
        GENERATE_INFOPLIST_FILE: true
        DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM_ID}
schemes:
  Kapal-Lawd:
    build:
      targets:
        Kapal-Lawd: all
        Kapal-LawdTests: all
    test:
      targets:
      - name: Kapal-LawdTests
      gatherCoverageData: true