name: Kapal-Lawd
settings:
  MARKETING_VERSION: ${MARKETING_VERSION}
  CURRENT_PROJECT_VERSION: ${CURRENT_PROJECT_VERSION}
  DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM_ID}
  SUPABASE_API_KEY: ${SUPABASE_API_KEY}
  SUPABASE_BASE_URL: ${SUPABASE_BASE_URL}
options:
  bundleIdPrefix: com.Kapal-Lawd
  resolvePackagesAutomatically: true
packages:
  SDBeaconScanner:
    url: https://github.com/SagarSDagdu/SDBeaconScanner.git
    from: 0.0.2
  Supabase:
    url: "https://github.com/supabase/supabase-swift.git"
    from: 2.0.0
targets:
  Kapal-Lawd:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    info:
        path: Kapal-Lawd/Info.plist
        properties:
          Privacy - Location Always and When In Use Usage Description: "Audium uses your location to provide an immersive audio experience as you navigate the exhibition. By detecting your proximity to specific exhibits, the app can automatically play relevant audio narrations at the right moment. Continuous location access is required to ensure seamless playback as you explore different sections of the gallery without needing to interact with your device."
          Privacy - Location When In Use Usage Description: "Audium requires access to your location while using the app to deliver a hands-free audio experience. When you approach an exhibit, Audium detects your proximity and plays a relevant audio narration. This location-based functionality allows for automatic, real-time content delivery without any additional interaction needed from you."
          Privacy - Bluetooth Always Usage Description: "Audium uses Bluetooth to detect your proximity to exhibits equipped with iBeacon. This allows the app to automatically play audio narrations when you approach each booth, enhancing your exhibition experience with hands-free interactions. Bluetooth detection is essential for delivering seamless, location-based audio content during your visit."
          Privacy - Bluetooth Peripheral Usage Description: "Audium requires Bluetooth access to connect with iBeacons at the exhibition. These beacons signal your proximity to different exhibits, allowing the app to automatically play relevant audio narrations as you move through the gallery. This enhances your experience by providing hands-free, location-aware content for each exhibit you encounter."
          NSAppTransportSecurity:
            NSAllowsArbitraryLoads: true
          UIBackgroundModes:
            - Audium needs continuous location updates to maintain accurate proximity detection as you move through the exhibition. This allows the app to play audio narrations at the right time without requiring you to actively keep the app open.
            - Audium plays audio content as you approach different exhibits, enhancing your experience with immersive narrations. Background audio playback ensures you can continue listening to narrations even when switching apps or locking your device.
            - Audium uses CoreBluetooth to connect with iBeacons at the exhibition. This connection enables the app to detect your proximity to different exhibits, triggering relevant audio narrations in real time as you navigate the gallery.
            - To deliver uninterrupted, hands-free audio narrations, Audium processes data in the background. This ensures that proximity to exhibits is continuously monitored, so you receive audio content seamlessly without needing to interact with your device.
            - Audium may occasionally need to download updated audio content or exhibit information to provide the best possible experience. Background downloading allows the app to stay current and deliver accurate narrations for each exhibit without interruption.
          BGTaskSchedulerPermittedIdentifiers:
            - "com.Kapal-Lawd.Kapal-Lawd.refresh"
            - "com.Kapal-Lawd.Kapal-Lawd.processing"
          UILaunchScreen:
            UIImageName: ""
          UISupportedInterfaceOrientations:
            - UIInterfaceOrientationPortrait
            - UIInterfaceOrientationPortraitUpsideDown
            - UIInterfaceOrientationLandscapeLeft
            - UIInterfaceOrientationLandscapeRight
          CFBundleIconName: "AppIcon"
          CFBundleDisplayName: "Audium"
          SUPABASE_API_KEY: ${SUPABASE_API_KEY}
          SUPABASE_BASE_URL: ${SUPABASE_BASE_URL}
    sources: [Kapal-Lawd]
    resources: [Resources]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.Kapal-Lawd.Kapal-Lawd
      INFOPLIST_FILE: Kapal-Lawd/Info.plist
      GENERATE_INFOPLIST_FILE: true
      DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM_ID}
    dependencies:
        - package: SDBeaconScanner
        - package: Supabase
  Kapal-LawdTests:
    type: bundle.unit-test
    platform: iOS
    sources: [Kapal-LawdTests]
    dependencies:
      - target: Kapal-Lawd
    settings:
      base:
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Kapal-Lawd.app/Kapal-Lawd"
        BUNDLE_LOADER: "$(TEST_HOST)"
        INFOPLIST_FILE: Kapal-Lawd/Info.plist
        GENERATE_INFOPLIST_FILE: true
        DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM_ID}
schemes:
  Kapal-Lawd:
    build:
      targets:
        Kapal-Lawd: all
        Kapal-LawdTests: all
    test:
      targets:
      - name: Kapal-LawdTests
      gatherCoverageData: true